INSERT INTO USER (id, name, score) VALUES (1	, 'Jack'	, 0	)
INSERT INTO USER (id, name, score) VALUES (2	, 'Joe'		, 0	)
INSERT INTO USER (id, name, score) VALUES (3	, 'James'	, 0	)
INSERT INTO USER (id, name, score) VALUES (4	, 'Aysha'	, 0	)
INSERT INTO USER (id, name, score) VALUES (5	, 'Lucy'	, 0	)

INSERT INTO ALLEGIANCE (allegianceId, allegiance) VALUES (1, 'Order')
INSERT INTO ALLEGIANCE (allegianceId, allegiance) VALUES (2, 'Chaos')
INSERT INTO ALLEGIANCE (allegianceId, allegiance) VALUES (3, 'Destruction')
INSERT INTO ALLEGIANCE (allegianceId, allegiance) VALUES (4, 'Death')

INSERT INTO ARMY (id, name, allegiance) VALUES (1, 'Seraphon', 'Order')

INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (1,	'Razordon',							'Order',	'Seraphon',		'Artillery',			1,	4,	60)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (2,	'Ripperdactyl',						'Order',	'Seraphon',		'-',					3,	12,	140)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (3,	'Salamander',						'Order',	'Seraphon',		'Artillery',			1,	4,	60)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (4,	'Terradon Rider',					'Order',	'Seraphon',		'-',					3,	12,	140)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (5,	'Saurus Warriors',					'Order',	'Seraphon',		'Battleline',			10,	40,	100)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (6,	'Skinks',							'Order',	'Seraphon',		'Battleline',			10,	40,	80)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (7,	'Bastiladon',						'Order',	'Seraphon',		'Behemoth',				1,	1,	300)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (8,	'Engine of the Gods',				'Order',	'Seraphon',		'Leader, Behemonth',	1,	1,	240)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (9,	'Stegadon',							'Order',	'Seraphon',		'Behemoth',				1,	1,	260)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (10,	'Trogolodon',						'Order',	'Seraphon',		'Behemoth',				1,	1,	200)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (11,	'Lord Kroak',						'Order',	'Seraphon',		'Leader',				1,	1,	540)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (12,	'Saurus Astrolith Bearer',			'Order',	'Seraphon',		'Leader',				1,	1,	160)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (13,	'Saurus Eternity Warder',			'Order',	'Seraphon',		'Leader',				1,	1,	140)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (14,	'Saurus Oldblood',					'Order',	'Seraphon',		'Leader',				1,	1,	100)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (15,	'Saurus Scar-Veteran on Cold One',	'Order',	'Seraphon',		'Leader',				1,	1,	100)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (16,	'Saurus Sunblood',					'Order',	'Seraphon',		'Leader',				1,	1,	120)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (17,	'Skink Priest',						'Order',	'Seraphon',		'Leader',				1,	1,	100)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (18,	'Skink Starpriest',					'Order',	'Seraphon',		'Leader',				1,	1,	100)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (19,	'Skink Starseer',					'Order',	'Seraphon',		'Leader',				1,	1,	160)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (20,	'Skink Starseer',					'Order',	'Seraphon',		'Leader',				1,	1,	260)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (21,	'Saurus Oldblood on Carnosaur',		'Order',	'Seraphon',		'Leader, Behemonth',	1,	1,	320)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (22,	'Saurus Scar-Veteran on Carnosaur',	'Order',	'Seraphon',		'Leader, Behemonth',	1,	1,	160)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (23,	'Chameleon Skinks',					'Order',	'Seraphon',		'-',					5,	20,	120)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (24,	'Kroxigor',							'Order',	'Seraphon',		'-',					3,	12,	180)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (25,	'Saurus Guard',						'Order',	'Seraphon',		'-',					5,	20,	100)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (26,	'Saurus Knights',					'Order',	'Seraphon',		'-',					5,	20,	120)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (27,	'Skink Handlers',					'Order',	'Seraphon',		'-',					3,	12,	40)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (28,	'Celestial Hurricanum',				'Order',	'Free Peoples',	'Behemoth',				1,	1,	320	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (29,	'Luminark of Hysh',					'Order',	'Free Peoples',	'Behemoth',				1,	1,	240	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (30,	'Battlemage',						'Order',	'Free Peoples',	'Leader',				1,	1,	100	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (31,	'Battlemage on Griffon',			'Order',	'Free Peoples',	'Leader, Behemoth',		1,	1,	280	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (32,	'Warrior Priest',					'Order',	'Free Peoples',	'Leader',				1,	1,	80	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (34,	'Witch Hunter',						'Order',	'Free Peoples',	'Leader',				1,	1,	60	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (35,	'War Altar of Sigmar',				'Order',	'Free Peoples',	'Leader, Behemoth',		1,	1,	300	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (36,	'Flagellants',						'Order',	'Free Peoples',	'-',					10,	40,	80	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (37,	'Freeguild Archers',				'Order',	'Free Peoples',	'Battleline'			10,	30,	100	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (38,	'Freeguild Guard',					'Order',	'Free Peoples',	'Battleline'			10,	40,	100	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (39,	'Freeguild Crossbowmen',			'Order',	'Free Peoples',	'Battleline'			10,	30,	80	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (40,	'Freeguild Handgunners',			'Order',	'Free Peoples',	'Battleline'			10,	30,	100	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (41,	'Freeguild General',				'Order',	'Free Peoples',	'Leader',				1,	1,	100	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (42,	'Freeguild General on Griffon',		'Order',	'Free Peoples',	'Leader, Behemoth',		1,	1,	300	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (43,	'Demigryph Knights',				'Order',	'Free Peoples',	'-',					3,	12,	200	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (45,	'Freeguild Greatswords',			'Order',	'Free Peoples',	'-',					10,	30,	160	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (46,	'Greeguild Outriders',				'Order',	'Free Peoples',	'-',					5,	20,	140	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (47,	'Freeguild Pistoliers,'				'Order',	'Free Peoples',	'-',					5,	20,	140	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (48,	'Cannon',							'Order',	'Dispossessed',	'Artillery',			1,	1,	180	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (49,	'Hellblaster Volley Gun',			'Order',	'Free Peoples',	'Artillery',			1,	1,	120	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (50,	'Hellstorm Rocket Battery',			'Order',	'Free Peoples',	'Artillery',			1,	1,	180	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (51,	'Organ Gun',						'Order',	'Dispossessed',	'Artillery',			1,	1,	120	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (52,	'Steam Tank',						'Order',	'Free Peoples',	'Behemoth',				1,	1,	300	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (53,	'Cogsmith',							'Order',	'Dispossessed',	'Artillery',			1,	1,	100	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (54,	'Gunmaster',						'Order',	'Free Peoples',	'Leader',				1,	1,	80	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (55,	'Gyrobombers',						'Order',	'Dispossessed',	'-',					1,	1,	80	)
INSERT INTO UNIT (id, name, allegiance, army, role, min, max, points) VALUES (56,	'Gyrocopters',						'Order',	'Dispossessed',	'-',					1,	1,	80	)
